### ISSUE TITLE
[BUG]:turbot_mod resource always plans an update to current_version

### ISSUE THREAD

**Issue by RupeshPatil20** [turbot/terraform-provider-turbot#38]
### Issue

turbot_mod resources always shows an update to current_version when a plan is run, even when the version is specified in the initial resource. This needlessly uses compute to modify the resource (and state) and clutters every plan with false information

example
```
resource "turbot_mod" "gcp" {
  parent  = var.turbot_parent
  org     = "turbot"
  mod     = "gcp"
  version = "5.8.1"
}
```

has a version specified but every plan post apply shows
```
resource "turbot_mod" "gcp" {
        id              = "123456789012345"
        mod             = "gcp"
        org             = "turbot"
        parent          = "123456789012345"
        parent_akas     = [
            "tmod:@turbot/turbot#/",
        ]
        uri             = "tmod:@turbot/gcp"
        version         = "5.8.1"
      ~ version_current = "5.8.1" -> (known after apply)
    }

```

### Expected behavior

turbot_mod does not modify the version_current unless the version is unset (default to `*`) or changing.

## Versions

```
$ terraform --version
Terraform v0.12.26
+ provider.turbot v1.0.4
```

**Comment by fatalbert3390** [comment]
There is a similar issue running mod updates where, if the `version` field is omitted or left blank, it says the latest version is the second-most-current version of the mod, instead of what is currently the newest. I've observed this with `aws`, `aws-iam` and `aws-kms`. After installing the mod, all subsequent `terraform apply` runs show that it’s going to update to the older version, but then don’t actually make any changes in the console:

<img width="590" alt="image" src="https://user-images.githubusercontent.com/25424055/86265748-31012780-bb92-11ea-87b8-282b1630b02c.png">
<img width="1687" alt="image" src="https://user-images.githubusercontent.com/25424055/86265796-45452480-bb92-11ea-89b3-384a1d8cb8c6.png">

**Comment by kaidaguerre** [comment]
We have reproduced the issue and are working on a fix.
